# staging build
FROM node:14.15-alpine AS builder

WORKDIR /app
ENV NODE_ENV staging
COPY package.json package-lock.json .env* /app/
RUN npm ci --ignore-scripts
COPY public /app/public
COPY src /app/src
RUN npm run build

# staging environment
FROM nginx:1.18-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
